ALTER TYPE activity_action ADD VALUE IF NOT EXISTS 'WORKLOG_ADDED';
ALTER TYPE activity_action ADD VALUE IF NOT EXISTS 'WORKLOG_UPDATED';
ALTER TYPE activity_action ADD VALUE IF NOT EXISTS 'WORKLOG_DELETED';
