---
spring:
  application:
    name: project-management-system
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mini-project-management-system?serverTimezone=Asia/Ho_Chi_Minh}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
# jwt:
#   secret: k8wT5KF1ZrFojvpXJbhXOcYVv44lCKvOwQudCRY6HjxxTGH3WQbQDHEFZjhS+mCE
#   header: Authorization
#   prefix: Bearer
#   expirationMs: 86400000 # 1 ngày tính bằng milliseconds
# common:
#   app:
#     name: My Application
#     version: 1.0.0
#
# app:
#   openapi:
#     server:
#       deployed: ${APP_OPENAPI_SERVER_DEPLOYED:https://backend-kltn-0-0-2.onrender.com}
